filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'bin/*'
        - 'library/*'
    paths: [ 'timeline/*']
tools:
    js_hint: true
    php_analyzer:
        enabled: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'bin/*'
            paths: {  }
        path_configs: {  }
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
            paths: {  }
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
            paths: {  }
    sensiolabs_security_checker: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]

changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'
before_commands: {  }
after_commands: {  }
artifacts: {  }
